#include <time.h>

#include "parse.h"

int main(int argc, char* argv[]){
    if(argc != 3)
        printf("Usage: ./%s <test_case>.txt <output_file>.txt\n", argv[0]);
    
    printf("Press 0 to exit.\n");
    printf("Press 1 to remove comments and print the comment free code on the console.\n");
    printf("Press 2 to printing the token list, generated by the lexer, on the console.\n");
    printf("Press 3 tp parse and print the parse tree appropriately.\n");
    printf("Press 4 to print the total time taken by the code (lexer and parser) on the console.\n");

    while(true){
        char choice;
        node* root = NULL;
        scanf("%c", &choice);

        switch (choice) {
            case '0':
                exit(EXIT_SUCCESS);
                break;
            
            case '1':
                //TODO
                break;

            case '2':
                FILE* input_file = fopen(argv[1], "r");
                if (!input_file) {
                    printf("Error: Could not open %s.\n", argv[1]);
                    exit(EXIT_FAILURE);
                }

                initializations();

                Token* token = NULL;
                while ((token = getNextToken(input_file)) != NULL) {
                    fprintf(stdout, "Token: %s, Lexeme: %s, Line: %d\n", 
                            tokenNameToString(token->name),  
                            token->lexeme,
                            token->lineno);
            
                    // free(token->lexeme);  // Free dynamically allocated lexeme
                    // free(token->value);    // Free value storage
                    // free(token);           // Free token itself
                }
                fclose(input_file);
            
                printf("\nLexical analysis complete.\n");
                break;
                
            case '3':
                root = parse_code("grammar.txt", argv[1]);
                print_parse_tree(root);       //Change this to in-order traversal and then write to file argv[2] 
                parse_tree_cleanup(&root);
                break;
            
            case '4':
                clock_t start_time, end_time;
                double total_CPU_time, total_CPU_time_in_seconds;
                start_time = clock();
                    root = parse_code("grammar.txt", argv[1]);
                end_time = clock();
                total_CPU_time = (double)(end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
                
                printf("Total CPU time: %lf\n", total_CPU_time);
                printf("Total CPU time in secs: %lf s\n", total_CPU_time_in_seconds);

                parse_tree_cleanup(&root);                
                break;

            default:
                printf("Error: Invalid choice.\n");
                break;
        }
    }
}
