#include <time.h>

#include "parse.h"

void removeComments(FILE* input_file) {
    char* temp = NULL;
    size_t bufferSize = 0;
    ssize_t characters;
    while ((characters = getline(&temp, &bufferSize, input_file)) != -1) {
        for (int i = 0; i < characters; i++) {
            if (temp[i] == '%') {
                printf("\n");
                break;
            }
            printf("%c", temp[i]);
        }
    }
    printf("\n");
    free(temp);
}

int main(int argc, char* argv[]){
    if(argc != 3){
        printf("Requires 3 arguments: Usage: %s <test_case>.txt <output_file>.txt\n", argv[0]);
        exit(EXIT_FAILURE);
    }
    FILE* input_file = fopen(argv[1], "r");
    if (!input_file) {
        printf("Error: Could not open %s.\n", argv[1]);
        exit(EXIT_FAILURE);
    }

    printf("\n                      \033[1;36mCS F363 - Compiler Project \033[1;92m(Group 14)\033[0m               \n");
    printf("\033[1;34m*********************************************************************************\033[0m\n");
    // TODO: Add IDs before submission
    printf("\033[1;35mTeam Members:\033[0m                                  \n");
    printf("\t- Abhiram H \n");
    printf("\t- Ankur Renduchintala\n");    
    printf("\t- Avyakth Kumar\n");
    printf("\t- Suchit Chebolu\n");
    printf("\t- Vikram Hariharan\n");
    printf("\n");   
    // TODO: Add more if necessary
    printf("\033[1;35mImplementation details:\033[0m                        \n");
    printf("\t- Both lexical and syntax analyzer modules implemented        \n");
    printf("\t- First and Follow sets automated                             \n");
    printf("\n"); 
    printf("\033[1;35mProgram:\033[0m                                       \n");

    while(true){
        printf("\033[1;34m+===============================================================================+\033[0m\n");
        printf("\033[1;34m|\033[0m                                      \033[1;32mMENU\033[0m                                     \033[1;34m|\033[0m\n");
        printf("\033[1;34m+===============================================================================+\033[0m\n");
        printf("\033[1;34m|\033[0m Press 0 to exit.                                                              \033[1;34m|\033[0m\n");
        printf("\033[1;34m|\033[0m Press 1 to remove comments and print the comment free code on the console.    \033[1;34m|\033[0m\n");
        printf("\033[1;34m|\033[0m Press 2 to printing the token list, generated by the lexer, on the console.   \033[1;34m|\033[0m\n");
        printf("\033[1;34m|\033[0m Press 3 tp parse and print the parse tree appropriately.                      \033[1;34m|\033[0m\n");
        printf("\033[1;34m|\033[0m Press 4 to print the total time taken by the code on the console.             \033[1;34m|\033[0m\n");
        printf("\033[1;34m+===============================================================================+\033[0m\n");
        printf("Enter your choice: ");

        char choice;
        node* root = NULL;
        scanf("\n%c", &choice);
        switch (choice) {
            case '0':
                printf("Exiting.\n");
                fclose(input_file);
                exit(EXIT_SUCCESS);
                break;
            
            case '1':
                removeComments(input_file);
                break;

            case '2':
                buffer_init(input_file);
                token* tok = NULL;
                while ((tok = get_next_token(input_file)) != NULL) {
                    if(tok->name != TK_EOF){
                        fprintf(stdout, "Line no. %-4d Token: %-15s Lexeme: %s\n", tok->line_num, token_to_string(tok->name), tok->lexeme);
                    }
                    else{
                        break;
                    }
                    free(tok);
                    tok = NULL;
                }
                free(tok);
                tok = NULL;
                printf("\nLexical analysis complete.\n");
                break;
                
            case '3':
                buffer_init(input_file);
                root = parse_code("grammar.txt", input_file);
                print_parse_tree_inorder(root);       //TODO Change this to in-order traversal and then write to file argv[2] 
                parse_tree_cleanup(&root);
                break;
            
            case '4':
                buffer_init(input_file);
                clock_t start_time, end_time;
                double total_CPU_time, total_CPU_time_in_seconds;
                start_time = clock();
                    root = parse_code("grammar.txt", input_file);
                end_time = clock();
                total_CPU_time = (double)(end_time - start_time);
                total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;
                
                printf("Total CPU time: %lf\n", total_CPU_time);
                printf("Total CPU time in secs: %lf s\n", total_CPU_time_in_seconds);

                parse_tree_cleanup(&root);                
                break;

            default:
                printf("Error: Invalid choice.\n");
                break;
        }

        rewind(input_file);
    }
}
